CREATE TABLE users(
	username VARCHAR(40) NOT NULL,
	fullname VARCHAR(40) NOT NULL,
    email VARCHAR(40) NOT NULL,
	admin INTEGER NOT NULL,
	password VARCHAR(256) NOT NULL,
	earnings REAL NOT NULL,
    created TIMESTAMP DEFAULT  CURRENT_TIMESTAMP NOT NULL,

	PRIMARY KEY(fullname)
);

CREATE TABLE artists(
	name VARCHAR(40) NOT NULL,
	owner VARCHAR(40) NOT NULL,
    created TIMESTAMP DEFAULT  CURRENT_TIMESTAMP NOT NULL,

	PRIMARY KEY(name),
	FOREIGN KEY(owner) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE projects(
	projectid INTEGER NOT NULL,
	releasedate VARCHAR(40) NOT NULL,
	title VARCHAR(40) NOT NULL,
	coverart VARCHAR(40) NOT NULL,
    created TIMESTAMP DEFAULT  CURRENT_TIMESTAMP NOT NULL,

	PRIMARY KEY(projectid)
);

CREATE TABLE tracks(
	trackid INTEGER NOT NULL,
	projectid INTEGER NOT NULL,
	title VARCHAR(40) NOT NULL,
	tracknumber INTEGER NOT NULL,
	upc INTEGER NOT NULL,
	isrc VARCHAR(12) NOT NULL,
	owner0 VARCHAR(40) NOT NULL,
	ownership0 REAL NOT NULL,
	owner1 VARCHAR(40) NOT NULL,
	ownership1 REAL NOT NULL,
	owner2 VARCHAR(40) NOT NULL,
	ownership2 REAL NOT NULL,
	owner3 VARCHAR(40) NOT NULL,
	ownership3 REAL NOT NULL,
	owner4 VARCHAR(40) NOT NULL,
	ownership4 REAL NOT NULL,
    created TIMESTAMP DEFAULT  CURRENT_TIMESTAMP NOT NULL,

	PRIMARY KEY(trackid),
    FOREIGN KEY(projectid) REFERENCES projects(projectid) ON DELETE CASCADE ON UPDATE CASCADE
    FOREIGN KEY(owner0) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE
    FOREIGN KEY(owner1) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE
    FOREIGN KEY(owner2) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE
    FOREIGN KEY(owner3) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE
    FOREIGN KEY(owner4) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE earnings(
	trackid INTEGER NOT NULL,
	payperiodstart VARCHAR(3) NOT NULL,
	amount REAL NOT NULL,
    created TIMESTAMP DEFAULT  CURRENT_TIMESTAMP NOT NULL,

	PRIMARY KEY(trackid, payperiodstart),
    FOREIGN KEY(trackid) REFERENCES tracks(trackid) ON DELETE CASCADE ON UPDATE CASCADE
    FOREIGN KEY(payperiodstart) REFERENCES payperiods(payperiodstart) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE payperiods(
	payperiodstart VARCHAR(3) NOT NULL,
	selected INTEGER NOT NULL,
	created TIMESTAMP DEFAULT  CURRENT_TIMESTAMP NOT NULL,

	PRIMARY KEY(payperiodstart)
);
